### PR TITLE
Hack to allow this crate to be used with Minecraft servers

### PR DESCRIPTION
**Pull request by ironhaven**
This pull has two changes and a new crate feature that allows this crate to reliably (one failure in about 7000 exec calls) send commands to the stock Notchian Minecraft server implementation.

First It changes `Packet::serialize` to buffer and send the full rcon packet in a single socket write. As apposed to many socket writes which may send many tcp packets to the server and cause a server error.

Second, there was a async delay added in the exec method that will send packets spaced apart to reduce the chance of a server error. Addtion delays could be added to the connect and exec methods to be more caution but in my testing additional delays did not improve reliability. This change was inspired by [this](https://bugs.mojang.com/browse/MC-72390) bug report.

The added delay code can be toggled off by disabling default featues on this crate in a Cargo manifest. I decided to make it default because 3 milliseconds is a short time for regular network applications and Minecraft servers should have first class support due to it being a common use case.

---
This change is [Reviewable](https://reviewable.io/reviews/panicbit/rust-rcon/12)

### CODE REVIEW

**Comment by panicbit** [comment]
Cool, thanks! I'l take a look at this in a few hours.

**Comment by ironhaven** [comment]
Oh for you information I also bumped the tokio version to 0.2.13. This should be fine right?

**Comment by ironhaven** [comment]
I am asking if we can make this a point release and push to crates.io. I am currenty depending on my fork and would like to just pull from crates.io

**Comment by panicbit** [comment]
Yes to both :)

**Comment by panicbit** [comment]
Again, thanks a lot!
I will some small changes and release a new version in a bit.

**Comment by panicbit** [comment]
Published on crates.io as `0.2.1`

**Pull request merged**
