### PR TITLE
Source engine example

### PR DESCRIPTION
**Pull request by jenrik**
Example of how to interact with a Source engine game.

Tested against Counter Strike: Global Offensive

---
This change is [Reviewable](https://reviewable.io/reviews/panicbit/rust-rcon/18)

### CODE REVIEW

**Comment by panicbit** [comment]
Looks good to me, thanks!

**Comment by jenrik** [comment]
The example should have been updated to use `#[async_std::main]` when #17 was merged

**Comment by panicbit** [comment]
Whoops 😅. I'll take care of it.

**Comment by panicbit** [comment]
I will also probably set up CI, so that stuff like this (or worse) doesn't happen again. https://github.com/panicbit/rust-rcon/issues/19

**Pull request merged**
