### PR TITLE
Add `Builder::connect_stream`

### PR DESCRIPTION
**Pull request by timvisee**
Add `Builder::connect_stream` to initialize an RCON connection over an existing `TcpStream`.

I need to inject a `PROXY` header on the TCP stream when it is opened. This allows me to do just that, by setting up the initial TCP connection myself.

---
This change is [Reviewable](https://reviewable.io/reviews/panicbit/rust-rcon/25)

### CODE REVIEW

**Comment by panicbit** [comment]
I will have a look at it in a few minutes 👍

**Comment by panicbit** [comment]
Published as `0.5.2` on `crates.io`.

**Comment by timvisee** [comment]
Awesome! Thanks for being so quick.

**Comment by panicbit** [comment]
I try my best.

**Pull request merged**
